[project]
name = "kiosk-backend-step1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "azure-cognitiveservices-speech>=1.48.2",
    "django>=6.0.2",
    "django-cors-headers>=4.9.0",
    "djangorestframework>=3.16.1",
    "fastapi>=0.135.1",
    "langchain>=1.2.10",
    "langchain-community>=0.4.1",
    "langchain-openai>=1.1.9",
    "openai>=2.18.0",
    "pillow>=12.1.0",
    "python-dotenv>=1.2.1",
    "uvicorn[standard]>=0.41.0",
]
