# Generated by Django 6.0.2 on 2026-02-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='메뉴명')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_images/', verbose_name='이미지')),
                ('is_spicy', models.BooleanField(default=False, verbose_name='매운맛')),
                ('is_cold', models.BooleanField(default=False, verbose_name='차가움')),
                ('is_hot', models.BooleanField(default=False, verbose_name='뜨거움')),
                ('category', models.CharField(choices=[('rice', '밥'), ('noodle', '면'), ('side', '사이드'), ('drink', '음료')], max_length=20, verbose_name='카테고리')),
                ('is_available', models.BooleanField(default=True, verbose_name='판매 가능')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '메뉴',
                'verbose_name_plural': '메뉴들',
            },
        ),
    ]
