# Generated by Django 6.0.2 on 2026-02-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='is_spicy',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_caffeine',
            field=models.BooleanField(default=True, verbose_name='카페인 포함'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('coffee', '커피'), ('latte', '라떼'), ('smoothie', '스무디'), ('tea', '티'), ('dessert', '디저트')], max_length=20, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_cold',
            field=models.BooleanField(default=False, verbose_name='ICE 가능'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='HOT 가능'),
        ),
    ]
